complex.csv:
  countryColumnName: country
  dataFileType: complex
  subjectColumnName: SUBJECT
  theme: complex
  timeColumnName: TIME
  valueColumnName: Value
time-expand.csv:
  countryColumnName: Country Code
  dataFileType: time-expand
  subjectColumnName: null
  theme: time-expand
  timeColumnName: null
  valueColumnName: null
time-in-column_1.csv:
  countryColumnName: Country
  dataFileType: time-in-column
  subjectColumnName: null
  theme: time-in-column_1
  timeColumnName: TIME
  valueColumnName: Value
