complex.csv:
  countryColumnName: LOCATION
  dataFileType: complex
  subjectColumnName: asd
  timeColumnName: asd
time-expand-0.csv:
  countryColumnName: country
  dataFileType: time-expand
  subjectColumnName: null
  timeColumnName: null
time-expand-1.csv:
  countryColumnName: Country Code
  dataFileType: time-expand
  subjectColumnName: null
  timeColumnName: null
time-in-column.csv:
  countryColumnName: LOCATION
  dataFileType: time-in-column
  subjectColumnName: null
  timeColumnName: asd
